### ISSUE TITLE
rewrite all of icanttellyou’s code

### ISSUE THREAD

**Issue by grkb-chaziz** [chazizgrkb/squarebracket#124]
we are still using a large chunk of code written by good old icty. this includes most of the JavaScript and well a few bits of Finalium SCSS.

When I cut ties with John due to drama, I quickly came out with new assets to replace his assets. When ICTY blocked me months ago because "fuck you", we didn't do shit and well we are still using his code.

**Comment by grkb-chaziz** [comment]
no.

**Comment by cr-contributors** [comment]
> When I cut ties with John due to drama

HAHHAHAHAHHAHAH

**Comment by PF94** [comment]
> > I quickly came out with new assets to replace his assets
> 
> the King of Spitefulness

His assets were using "pirated adobe fonts", but this isn't my project anymore, and i've seen you've went back using the John logos. It's fine honestly, Adobe's lawyers won't care.
