### ISSUE TITLE
cheeseRox Randley (sic) layout: The new cheeseRox

### ISSUE THREAD

**Issue by PF94** [chazizgrkb/squarebracket#127]
As of writing this, it's February 2022, 1 year after cheeseRox's predecessor PokTube launched. cheeseRox is currently undergoing an identity crisis along with growing pains. Maybe it's time to completely redo the concept of cheeseRox?

sbNext was gonna be the future of cheeseRox, but we were starting to have issues with how clunky and bloated the code has become. As such, sbNext has been cancelled in favor of the Randley (sic) layout, which will still use the sbNext Finalium SCSS for the time being. We will attempt to clean up the SCSS by removing old leftovers from when we were still largely using Roller's Principia Web's UI (besides the forums' scss). We will not be using any sounds or the pre-existing javascript file as that came from the old Bootstrap layout. So essentially we would have to rewrite everything from scratch.

Videos, images and music will now be referred to as posts, and we're considering making them more similar internally. The main page will no longer contain any content, as that will go to the browse page, which should hopefully feature more shit than videos in the near future. Video thumbnails should finally be replaceable and should finally no longer be only 16:9. The ID system will also be different, as instead of randomly generated base64 strings, it will be the internal incrementing number. Additionally, music and images will be internally the same thing as videos, and they will now be referred to as posts. This will make shit a lot easier to handle.

**Comment by jkrosado** [comment]
> sic

this is not proper context for a sic

**Comment by cleber299** [comment]
> > sic
> 
> this is not proper context for a sic

gamepedo told me that "randley" came from "radley", some bluey character that he has diaper porn of.

**Comment by cleber299** [comment]
Cancelled... we will now use Bootstrap 69.

**Comment by PF94** [comment]
scrapped in favor of improving pre-existing finalium frontend.

randley's scss was gonna be finalium (check the old main branch) anyways so whatever

**Comment by PF94** [comment]
just realized i wrote the the same thing twice in the same paragraph LMFAO

> Videos, images and music will now be referred to as posts, and we're considering making them more similar internally.

> Additionally, music and images will be internally the same thing as videos, and they will now be referred to as posts.
